'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ArInvoice
    Public Property Customer As String
    Public Property Invoice As String
    Public Property DocumentType As String
    Public Property NextPaymEntry As Decimal
    Public Property InvoiceDate As Nullable(Of Date)
    Public Property SalesOrder As String
    Public Property CustomerPoNumber As String
    Public Property Salesperson As String
    Public Property Branch As String
    Public Property Area As String
    Public Property TermsCode As String
    Public Property OrigDiscValue As Decimal
    Public Property InvoiceBal1 As Decimal
    Public Property InvoiceBal2 As Decimal
    Public Property InvoiceBal3 As Decimal
    Public Property InvoiceYear As Decimal
    Public Property InvoiceMonth As Decimal
    Public Property YearInvBalZero As Decimal
    Public Property MonthInvBalZero As Decimal
    Public Property LastDelNote As String
    Public Property StoreNumber As String
    Public Property ProofOfDelivery As String
    Public Property PodEntryDate As Nullable(Of Date)
    Public Property PodReference As String
    Public Property CurrencyValue As Decimal
    Public Property PostCurrency As String
    Public Property ConvRate As Decimal
    Public Property MulDiv As String
    Public Property AccountCur As String
    Public Property AccConvRate As Decimal
    Public Property AccMulDiv As String
    Public Property TriangCurrency As String
    Public Property TriangRate As Decimal
    Public Property TriangMulDiv As String
    Public Property RetentionInv As String
    Public Property TaxStatus As String
    Public Property TaxPortion As Decimal
    Public Property FixExchangeRate As String
    Public Property NextRevalNo As Decimal
    Public Property TaxCode As String
    Public Property DiscBal As Decimal
    Public Property PaymentRunFlag As String
    Public Property CollectionRunFlag As String
    Public Property InvoicePdcFlag As String
    Public Property TimeStamp As Byte()
    Public Property OrigInvRate As Decimal

    Public Overridable Property SorMaster As SorMaster

End Class
