'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports InvoicePay.Entity

Namespace InvoicePay.Entity

    Partial Public Class SysproCompanyC_7Entities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=SysproCompanyC_7Entities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property SorMasters() As DbSet(Of SorMaster)
        Public Overridable Property ArInvoices() As DbSet(Of ArInvoice)
    
    End Class

End Namespace
