'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InvMaster
    Public Property ID As Integer
    Public Property StockCode As String
    Public Property Description As String
    Public Property Category As String
    Public Property StockUom As String
    Public Property AlternateUom As String
    Public Property ConvFactAltUom As Nullable(Of Decimal)
    Public Property Picture As Byte()

    Public Overridable Property InvCategory As InvCategory
    Public Overridable Property InvWarehouses As ICollection(Of InvWarehouse) = New HashSet(Of InvWarehouse)

End Class
