'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InvMovement
    Public Property MovementID As Integer
    Public Property StockCode As String
    Public Property Warehouse As String
    Public Property TrnYear As Decimal
    Public Property TrnMonth As Decimal
    Public Property TrnDay As Decimal
    Public Property TrnTime As Date
    Public Property MovementType As String
    Public Property TrnQty As Decimal
    Public Property TrnValue As Nullable(Of Decimal)
    Public Property TrnType As String
    Public Property Document As Nullable(Of Decimal)
    Public Property Customer As String
    Public Property CustomerPoNumber As String
    Public Property Supplier As String
    Public Property OurRef As String
    Public Property TrnUser As String
    Public Property UnitPrice As Nullable(Of Decimal)

    Public Overridable Property InvWarehouse As InvWarehouse

End Class
