'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InvWarehouse
    Public Property StockCode As String
    Public Property Warehouse As String
    Public Property QtyOnhand As Nullable(Of Decimal)
    Public Property MtdQtyReceived As Nullable(Of Decimal)
    Public Property MtdQtySold As Nullable(Of Decimal)
    Public Property QtyOnOrder As Nullable(Of Decimal)
    Public Property QtyOnBackOrder As Nullable(Of Decimal)
    Public Property YtdQtySold As Nullable(Of Decimal)
    Public Property DateLastEntry As Nullable(Of Date)

    Public Overridable Property InvMovements As ICollection(Of InvMovement) = New HashSet(Of InvMovement)
    Public Overridable Property InvWhMaster As InvWhMaster
    Public Overridable Property InvMaster As InvMaster

End Class
