'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InvoicePayDetail
    Public Property ID As Integer
    Public Property SalesOrder As String
    Public Property Invoice As String
    Public Property InvoiceValue As Nullable(Of Decimal)
    Public Property InvoiceDate As Nullable(Of Date)
    Public Property Balance As Nullable(Of Decimal)
    Public Property CreditNoteValue As Nullable(Of Decimal)
    Public Property Contra As Nullable(Of Decimal)
    Public Property Retention As Nullable(Of Decimal)
    Public Property BalanceAfterRetenContra As Nullable(Of Decimal)
    Public Property Other As Nullable(Of Decimal)
    Public Property OtherComment As String
    Public Property Comment As String
    Public Property Remark As String
    Public Property PayDate As Nullable(Of Date)
    Public Property PayAmount As Nullable(Of Decimal)
    Public Property PayDate1 As Nullable(Of Date)
    Public Property PayAmount1 As Nullable(Of Decimal)
    Public Property PayDate2 As Nullable(Of Date)
    Public Property PayAmount2 As Nullable(Of Decimal)
    Public Property PayDate3 As Nullable(Of Date)
    Public Property PayAmount3 As Nullable(Of Decimal)
    Public Property PayDate4 As Nullable(Of Date)
    Public Property PayAmount4 As Nullable(Of Decimal)
    Public Property PayDate5 As Nullable(Of Date)
    Public Property PayAmount5 As Nullable(Of Decimal)

End Class
