'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Actom.SysproTrigger.DAL

    Partial Public Class PorMasterHdr_
        Public Property PurchaseOrder As String
        Public Property Incoterms As String
        Public Property TimeStamp As Byte()
        Public Property ConsigneeOrderNo As String
        Public Property Packaging As String
        Public Property MethodOfPayment As String
        Public Property YourTenderOf As String
        Public Property PortOfEntry As String
        Public Property ForwardingAgentDet As String
        Public Property For002 As String
        Public Property For003 As String
        Public Property ForwardCoverRequir As String
        Public Property FobDate As Nullable(Of Date)
        Public Property SubstationName As String
        Public Property Confirmed As String
        Public Property ConfirmedDate As String
        Public Property IncotermPort As String
        Public Property DeliveryMethod As String
        Public Property Attn As String
    
    End Class

End Namespace
