'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Actom.SysproTrigger.DAL

    Partial Public Class ReqDetail
        Public Property Originator As String
        Public Property Requisition As String
        Public Property Line As Decimal
        Public Property ReqnStatus As String
        Public Property StockCode As String
        Public Property StockDescription As String
        Public Property OrderQty As Decimal
        Public Property OrderUom As String
        Public Property DateReqnRaised As Nullable(Of Date)
        Public Property DueDate As Nullable(Of Date)
        Public Property ReasonForReqn As String
        Public Property Supplier As String
        Public Property Price As Decimal
        Public Property PriceUom As String
        Public Property DiscPct1 As Decimal
        Public Property DiscPct2 As Decimal
        Public Property DiscPct3 As Decimal
        Public Property DiscountCode As String
        Public Property Warehouse As String
        Public Property SupCatalogueNum As String
        Public Property Job As String
        Public Property JobLine As String
        Public Property GlCode As String
        Public Property ProductClass As String
        Public Property TaxCode As String
        Public Property Customer As String
        Public Property CustomerPoNumber As String
        Public Property CapexNum As String
        Public Property ReqnOnHoldFlag As String
        Public Property ReasonForHold As String
        Public Property HoldUser As String
        Public Property ConfirmedPoNum As String
        Public Property ConfirmedPoLine As Decimal
        Public Property DatePoConfirmed As Nullable(Of Date)
        Public Property Buyer As String
        Public Property CurrentHolder As String
        Public Property HoldersRouteNum As Decimal
        Public Property DateActioned As Nullable(Of Date)
        Public Property ReceiptFlag As String
        Public Property DateLastReceipt As Nullable(Of Date)
        Public Property AckReceiptFlag As String
        Public Property SalesOrder As String
        Public Property SalesOrderLine As Decimal
        Public Property PrintedFlag As String
        Public Property OrderDate As Nullable(Of Date)
        Public Property HierHead As String
        Public Property Section1 As String
        Public Property Section2 As String
        Public Property Section3 As String
        Public Property Section4 As String
        Public Property SubOperationNum As Decimal
        Public Property Quote As String
        Public Property QuoteVersion As Decimal
        Public Property QuoteLineNum As Decimal
        Public Property InspectNonStkRec As String
        Public Property DocumentFormat As String
        Public Property EccHold As String
        Public Property Version As String
        Public Property Release As String
        Public Property UserCode As String
        Public Property BpoApproved As String
        Public Property [Operator] As String
        Public Property CurrentOperator As String
        Public Property AssetFlag As String
        Public Property CapexLine As Decimal
        Public Property CapexCode As String
        Public Property RequisitionType As String
        Public Property IssueWarehouse As String
        Public Property ApprovedDate As Nullable(Of Date)
        Public Property SelectionCode As String
        Public Property SelectionType As String
        Public Property AutoVoucherReqd As String
        Public Property ShippingLocation As String
        Public Property DeliveryTerms As String
        Public Property IncludeInMrp As String
        Public Property TimeStamp As Byte()
        Public Property WithTaxExpenseType As String
    
    End Class

End Namespace
